language: objective-c
osx_image: beta-xcode6.3
branches:
  only:
    - master
    - develop
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -project CoreDataQueryInterface.xcodeproj -scheme "CoreDataQueryInterface iOS" -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c
  - xcodebuild -project CoreDataQueryInterface.xcodeproj -scheme "CoreDataQueryInterface OSX" -sdk macosx10.10
    -destination "platform=OS X,arch=x86_64" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c
  - pod lib lint --quick
