language: objective-c
osx_image: xcode7
branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -project CoreDataQueryInterface.xcodeproj -scheme "CoreDataQueryInterface iOS" -sdk iphonesimulator9.0
    -destination "platform=iOS Simulator,name=iPhone 6" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -project CoreDataQueryInterface.xcodeproj -scheme "CoreDataQueryInterface OSX" -sdk macosx10.11
    -destination "platform=OS X,arch=x86_64" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - pod lib lint --quick
