language: objective-c
osx_image: xcode63
branches:
  only:
    - master
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
- travis_retry gem install xcpretty -N
script:
- set -o pipefail
- xcodebuild -project CoreDataQueryInterface.xcodeproj -scheme "CoreDataQueryInterface iOS" -sdk iphonesimulator
  -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c

