language: objective-c
osx_image: xcode7.2
branches:
  only:
    - master
env:
  global: 
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - IOS_SDK=iphonesimulator9.2
    - OSX_SDK=macosx10.11
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="CoreDataQueryInterface iOS" SDK="$IOS_SDK" POD_LINT="YES"
    - DESTINATION="OS=8.2,name=iPhone 5" SCHEME="CoreDataQueryInterface iOS" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="CoreDataQueryInterface iOS" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="CoreDataQueryInterface iOS" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SCHEME="CoreDataQueryInterface iOS" SDK="$IOS_SDK" POD_LINT="NO"
    - DESTINATION="arch=x86_64" SCHEME="CoreDataQueryInterface OSX" SDK="$OSX_SDK" POD_LINT="NO"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project CoreDataQueryInterface.xcodeproj -scheme "$SCHEME" -sdk $SDK -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - if [ $POD_LINT = "YES" ]; then
      pod lib lint --quick;
    fi
