//
// Generated by CDQI on 2016-03-31.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

class DepartmentAttribute: Attribute, Aggregable, TypedExpressionConvertible {
    typealias ValueType = Department
    private(set) lazy var name: StringAttribute = { StringAttribute("name", parent: self) }()
    private(set) lazy var employees: EntityCollectionAttribute<Employee> = { EntityCollectionAttribute<Employee>("employees", parent: self) }()
}

extension Department: EntityType {
    typealias EntityAttributeType = DepartmentAttribute
}

