//
// Generated by CDQI on 2016-03-31.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

class DepartmentAttribute: Attribute, Aggregable {
    private(set) lazy var name: StringAttribute = { StringAttribute("name", parent: self) }()
    private(set) lazy var employees: EmployeeAttribute = { EmployeeAttribute("employees", parent: self) }()
}

extension Department: EntityType {
    typealias EntityAttributeType = DepartmentAttribute
}

