//
// Generated by CDQI on 2015-12-30.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

class EmployeeAttribute: Attribute, Aggregable {
    private(set) lazy var firstName: StringAttribute = { StringAttribute("firstName", parent: self) }()
    private(set) lazy var lastName: KeyAttribute = { KeyAttribute("lastName", parent: self) }()
    private(set) lazy var nickName: KeyAttribute = { KeyAttribute("nickName", parent: self) }()
    private(set) lazy var salary: NumericAttribute = { NumericAttribute("salary", parent: self) }()
    private(set) lazy var department: DepartmentAttribute = { DepartmentAttribute("department", parent: self) }()
}

extension Employee: EntityType {
    typealias EntityAttributeType = EmployeeAttribute
}

