//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

public final class TestEntityAttribute: EntityAttribute, Subqueryable {
    public private(set) lazy var binary: DataAttribute = { DataAttribute(key: "binary", parent: self) }()
    public private(set) lazy var boolean: BoolAttribute = { BoolAttribute(key: "boolean", parent: self) }()
    public private(set) lazy var date: DateAttribute = { DateAttribute(key: "date", parent: self) }()
    public private(set) lazy var decimal: DecimalAttribute = { DecimalAttribute(key: "decimal", parent: self) }()
    public private(set) lazy var double: DoubleAttribute = { DoubleAttribute(key: "double", parent: self) }()
    public private(set) lazy var float: FloatAttribute = { FloatAttribute(key: "float", parent: self) }()
    public private(set) lazy var integer16: Int16Attribute = { Int16Attribute(key: "integer16", parent: self) }()
    public private(set) lazy var integer32: Int32Attribute = { Int32Attribute(key: "integer32", parent: self) }()
    public private(set) lazy var integer64: Int64Attribute = { Int64Attribute(key: "integer64", parent: self) }()
    public private(set) lazy var string: StringAttribute = { StringAttribute(key: "string", parent: self) }()
}

extension TestEntity: Entity {
    public typealias CDQIEntityAttribute = TestEntityAttribute
}

