//
// Generated by CDQI on 2016-01-02.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

class ArtistAttribute: Attribute, Aggregable {
    private(set) lazy var name: KeyAttribute = { KeyAttribute("name", parent: self) }()
    private(set) lazy var songs: SongAttribute = { SongAttribute("songs", parent: self) }()
}

extension Artist: EntityType {
    typealias EntityAttributeType = ArtistAttribute
}

