//
// Generated by CDQI on 2016-04-06.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

class ArtistAttribute: EntityAttribute, Aggregable {
    private(set) lazy var name: StringAttribute = { StringAttribute("name", parent: self) }()
    private(set) lazy var songs: SongAttribute = { SongAttribute("songs", parent: self) }()
}

extension Artist: EntityType {
    typealias EntityAttributeType = ArtistAttribute
}

