//
// Generated by CDQI on 2016-01-02.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

class SongAttribute: Attribute, Aggregable {
    private(set) lazy var name: KeyAttribute = { KeyAttribute("name", parent: self) }()
    private(set) lazy var position: KeyAttribute = { KeyAttribute("position", parent: self) }()
    private(set) lazy var year: KeyAttribute = { KeyAttribute("year", parent: self) }()
    private(set) lazy var artist: ArtistAttribute = { ArtistAttribute("artist", parent: self) }()
}

extension Song: EntityType {
    typealias EntityAttributeType = SongAttribute
}

