//
// Generated by CDQI on 2016-10-14.
//
// This file was generated by a tool. Further invocations of this tool will overwrite this file.
// Edit it at your own risk.
//

import CoreDataQueryInterface

final class SongAttribute: EntityAttribute, Subqueryable {
    private(set) lazy var name: StringAttribute = { StringAttribute(key: "name", parent: self) }()
    private(set) lazy var position: Integer32Attribute = { Integer32Attribute(key: "position", parent: self) }()
    private(set) lazy var year: Integer32Attribute = { Integer32Attribute(key: "year", parent: self) }()
    private(set) lazy var artist: ArtistAttribute = { ArtistAttribute(key: "artist", parent: self) }()
}

extension Song: Entity {
    typealias CDQIAttribute = SongAttribute
}

